Update tmux source

diff --git a/build b/build
--- a/build
+++ b/build
@@ -17,7 +17,7 @@ if [ -n "${ZSH_VERSION:-}" ]; then
 fi
 
 usage="$(cat <<\END
-Usage: build [-m ARCH] [-c CPU] [-i IMAGE] [-d CMD]
+Usage: build [-s SYS] [-m ARCH] [-c CPU] [-i IMAGE] [-d CMD]
 
 Creates an archive containing statically-linked, hermetic,
 patched tmux. Installation of the patched tmux from the
@@ -27,6 +27,8 @@ it will work.
 
 Options:
 
+  -s SYS    `uname -s` from the target machine; defaults to `uname -s`
+            from the local machine
   -m ARCH   `uname -m` from the target machine; defaults to `uname -m`
             from the local machine
   -c CPU    generate machine instructions for CPU of this type; this
@@ -73,13 +75,13 @@ ncurses_version=6.2
 kitty_version=0.17.4
 termite_version=15
 kakoune_version=2020.09.01
-tmux_version=3.3-rc-109-gc7729479-z4h
+tmux_version=3.3-rc-109-ga9f25577-z4h
 
 ncurses_url=https://ftp.gnu.org/pub/gnu/ncurses/ncurses-$ncurses_version.tar.gz
-tmux_url=https://github.com/romkatv/tmux/archive/$tmux_version.tar.gz
+tmux_url=https://github.com/bdentino/tmux/archive/$tmux_version.tar.gz
 
 ncurses_sha256=30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d
-tmux_sha256=bcaab9aa1ed7313b3ae867e8fbfb986aed2f422e7f77d798ec8384b88cc53cd6
+tmux_sha256=956cfbf04ad76cc3ceeb86e6f308b8517f09e5e952b0204c874ed14f69fda425
 
 cpus="$(getconf _NPROCESSORS_ONLN)" || cpus="$(sysctl -n hw.ncpu)" || cpus=8
 
@@ -291,12 +293,24 @@ docker=
 
 TMUX_BIN_ARCH=
 TMUX_BIN_CPU=
+TMUX_BIN_KERNEL=
 
-while getopts ':m:c:i:d:h' opt "$@"; do
+while getopts ':s:m:c:i:d:h' opt "$@"; do
   case "$opt" in
     h)
       printf '%s\n' "$usage"
       exit
+    ;;
+    s)
+      if [ -n "$TMUX_BIN_KERNEL" ]; then
+        >&2 echo "[error] duplicate option: -$opt"
+        exit 1
+      fi
+      if [ -z "$OPTARG" ]; then
+        >&2 echo "[error] incorrect value of -$opt: $OPTARG"
+        exit 1
+      fi
+      TMUX_BIN_KERNEL="$OPTARG"
     ;;
     m)
       if [ -n "$TMUX_BIN_ARCH" ]; then
@@ -375,14 +389,16 @@ if [ -z "$TMUX_BIN_CPU" ]; then
   esac
 fi
 
-TMUX_BIN_KERNEL="$(uname -s)"
-TMUX_BIN_KERNEL="$(printf '%s' "$TMUX_BIN_KERNEL" | tr '[A-Z]' '[a-z]')"
+if [ -z "$TMUX_BIN_KERNEL" ]; then
+  TMUX_BIN_KERNEL="$(uname -s)"
+  TMUX_BIN_KERNEL="$(printf '%s' "$TMUX_BIN_KERNEL" | tr '[A-Z]' '[a-z]')"
+fi
 
 case "$TMUX_BIN_KERNEL" in
   linux)
     if [ -z "$image" ]; then
       case "$TMUX_BIN_ARCH" in
-        x86_64)         image=alpine:3.9.5;;
+        x86_64)         image=amd64/alpine:3.9.5;;
         i386|i586|i686) image=i386/alpine:3.9.5;;
         armv6l)         image=arm32v6/alpine:3.9.5;;
         armv7l)         image=arm32v7/alpine:3.9.5;;
